POST  http://localhost:3000/login
content-type: application/json

{
    "user": "sdfsdfsde2@mail.com",
    "password": "tes2esd"
}

###

POST  http://localhost:3000/register
content-type: application/json

{
    "name": "brain",
    "email": "sd@mfail.com",
    "password": "tes2esf",
    "phoneNumber": "1223223433",
    "id": "iffsd"
}

###

POST  http://localhost:3000/add-task
content-type: application/json

{
    "title": "halo bro",
    "description": "ciba",
    "id": "brian12345",
    "maxTime": "2021-05-22 06:39:00.000Z"
}

###

PATCH  http://localhost:3000/update-task
content-type: application/json

{
    "title": "sdfsdfsde2@mail.com",
    "description": "tes2esd",
    "id": "1",
    "taskId": "609c0f2eeb082d0f874cf8fd"
}

###

DELETE  http://localhost:3000/delete-task
content-type: application/json

{
    "taskId": "609c0f2eeb082d0f874cf8fd"
}

###

PATCH  http://localhost:3000/update-customer?method=delete
content-type: application/json

{
    "id": "idw2w",
    "connections": ["tes", "bre"]
}

###

POST  http://localhost:3000/add-comment
content-type: application/json

{
    "taskId": "60a6925ce07c8b281b11dea2",
    "comment": "baru lagiasddsf",
    "userId": "cik123"
}

###

PATCH  http://localhost:3000/update-profile
content-type: application/json

{
    "id": "pochinki",
    "name": "1"
}